apiVersion: v1
kind: ConfigMap
metadata:
  name: plagiarismguard-app-config
  namespace: plagiarismguard
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_TELEMETRY_DISABLED: "1"
  LDAP_ENABLED: "true"
  LDAP_URL: "ldaps://ldap.bsuir.by"
  LDAP_BASE_DN: "dc=bsuir,dc=by"
  LDAP_USER_SEARCH_FILTER: "(uid={username})"
  LDAP_USERNAME_ATTRIBUTE: "uid"
  LDAP_EMAIL_ATTRIBUTE: "mail"
  LDAP_FIRSTNAME_ATTRIBUTE: "givenName"
  LDAP_LASTNAME_ATTRIBUTE: "sn"
  LDAP_MIDDLENAME_ATTRIBUTE: "middleName"
  LDAP_TIMEOUT: "10000"
