apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plagiarismguard
resources:
  - namespace.yaml
  - configmap-app.yaml
  - pvc-data.yaml
  - deployment-app.yaml
  - service-app.yaml
  - configmap-nginx.yaml
  - deployment-nginx.yaml
  - service-nginx.yaml
  - ingress.yaml
