apiVersion: v1
kind: Secret
metadata:
  name: plagiarismguard-app-secret
  namespace: plagiarismguard
type: Opaque
stringData:
  NEXT_PUBLIC_APP_URL: "https://guard-main.by"
  LDAP_BIND_DN: "uid=smdoadmin,ou=staff,dc=bsuir,dc=by"
  LDAP_BIND_PASSWORD: "replace-me"
  LDAP_USER_SEARCH_BASES: "ou=staff,dc=bsuir,dc=by;ou=stud,dc=bsuir,dc=by"
